// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"shaps.api/controller"
	"shaps.api/domain"
	"shaps.api/domain/setting"
	"shaps.api/infrastructure"
	"shaps.api/repository"
)

// Injectors from wire.go:

func InitializeHandler(s setting.Setting) *Routing {
	db := infrastructure.NewDb(s)
	subscriptionRepository := repository.NewSubscriptionRepository(db)
	createSubscriptionInteractor := domain.NewCreateSubscriptionInteractor(subscriptionRepository)
	subscriptionController := controller.NewSubscriptionController(createSubscriptionInteractor)
	routing := NewRouting(subscriptionController, s)
	return routing
}
